language: generic

matrix:
  include:
    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-cuda
        - DOCKERTAG=8.0
        - CUDA_VER=8.0
        
    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-cuda
        - DOCKERTAG=9.0
        - CUDA_VER=9.0
        
    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-cuda
        - DOCKERTAG=9.1
        - CUDA_VER=9.1
        
    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-cuda
        - DOCKERTAG=9.2
        - CUDA_VER=9.2

    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-cuda
        - DOCKERTAG=10.0
        - CUDA_VER=10.0

    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-cuda
        - DOCKERTAG=10.1
        - CUDA_VER=10.1

    - os: linux
      env:
        - DOCKERIMAGE=linux-anvil-cuda
        - DOCKERTAG=10.2
        - CUDA_VER=10.2

before_install:
    # Enable experimental features (needed for squash)
    - sudo cp docker_daemon_config.json /etc/docker/daemon.json
    - sudo service docker restart

    - docker info
    - |
      if [ "$(uname -m)" = "x86_64" ]; then
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      fi
      export QEMU_STATIC_VERSION=v3.1.0-3
      qemu_ppc64le_sha256=d018b96e20f7aefbc50e6ba93b6cabfd53490cdf1c88b02e7d66716fa09a7a17
      qemu_aarch64_sha256=a64b39b8ce16e2285cb130bcba7143e6ad2fe19935401f01c38325febe64104b
      qemu_arm_sha256=f4184c927f78d23d199056c5b0b6d75855e298410571d65582face3159117901
      wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_STATIC_VERSION}/qemu-ppc64le-static
      wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_STATIC_VERSION}/qemu-aarch64-static
      wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_STATIC_VERSION}/qemu-arm-static
      sha256sum qemu-ppc64le-static | grep -F "${qemu_ppc64le_sha256}"
      sha256sum qemu-aarch64-static | grep -F "${qemu_aarch64_sha256}"
      sha256sum qemu-arm-static | grep -F "${qemu_aarch64_sha256}"
      chmod +x qemu-ppc64le-static
      chmod +x qemu-aarch64-static
      chmod +x qemu-arm-static

install:
    - |
      if [[ $DOCKERTAG == "jnlp-slave" ]]
      then
        sed "s|@BASE_IMAGE@|condaforge/${DOCKERIMAGE}|" jnlp-slave/Dockerfile.in > $DOCKERIMAGE/Dockerfile
      fi
    - docker build --build-arg CUDA_VER -t condaforge/$DOCKERIMAGE:$DOCKERTAG -f $DOCKERIMAGE/Dockerfile --no-cache --squash .

script:
    - |
      if [[ $DOCKERTAG != "jnlp-slave" ]]
      then
        ./.circleci/run_docker_build.sh
      fi

deploy:
  provider: script
  script: docker login -u jaimergp -p $DH_PASSWORD && docker push jaimergp/$DOCKERIMAGE:$DOCKERTAG
